### ISSUE TITLE
Latex typesetting: roman subscript in Teff.

### ISSUE THREAD

**Issue by demink** [rjfarmer/mesaplot#19]
## Expected Behavior
Typesetting of the axis label for the effective temperature T_eff should probably follow common practice for typesetting and use the subscript in roman:  `$T_{\rm eff}$`

## Actual Behavior
The "eff" is now typeset in italic ( latex for e times f times f).  The `\rm` is probably missing.
![image](https://user-images.githubusercontent.com/12985691/53751742-420e2b80-3ead-11e9-9ff5-d3efbd363b7c.png)

## Steps to Reproduce the Problem

  1. Load history file
  1. `p.plotHistory(m,xaxis='star_age',y1='log_center_T',y2='he_core_mass')`
  

## Specifications

  - Version: Latest
  - Platform: OSX

**Comment by demink** [comment]
Simply adding `\rm` on line 385 and 387 in `plot.py` works but leads to labels that are very small.  
![image](https://user-images.githubusercontent.com/12985691/53751608-ef347400-3eac-11e9-85d9-c019341ca961.png)

**Comment by rjfarmer** [comment]
So i made the fix for the roman eff in d64a18e. On linux the text size stays the same, so must be a mac issue. One thing to see is if saving the figure, things render properly as there are a few graphical issues which resolve themselves when the plot is saved rather than rendered to screen.

import matplotlib.pyplot as plt
p.plotHistory(m,xaxis='star_age',y1='log_center_T',y2='he_core_mass')
plt.savefig('plot.pdf')
